rustformers/llm

llama-rs/src/main.rs

Another simple fix - removes the hardcoded model path.
Fixes #2.

fix(main): use args.model_path

---

ggml-raw/build.rs

This turns on the individual flags based on the target features of the host for both Linux and Windows x86-64. Support for other architectures is possible, but I haven't done it because I don't have a way to test them.
There is one pretty large annoyance with this - you need to explicitly supply feature flags, because rustc won't automatically turn them on: 
```sh
RUSTFLAGS='-C target-feature=+avx2,+fma,+f16c'
```
(also, `f16c` was only stabilised in 1.68.0...)
I haven't been able to find a way to detect this automatically for the target (and not for the host); I'm also not sure if it would necessarily be a good idea (I can think of people deploying to old / low-power x86 machines).

feat(raw): make build script more resilient

---

llama-cli/src/cli_args.rs
llama-cli/src/main.rs

Implements #27 (at least the part we *can* implement, deterministic floating point math is out of scope for the project).
This allows specifying a `--seed` value in `llama-cli`. If no value is passed, the rng is seeded from system entropy like before.

Adds a way to specify the seed for RNG

---

llama-cli/src/main.rs
llama-rs/src/lib.rs

This pull request added a simple struct `InferenceStats` for capturing the model evaluation stats. This struct can generate a similar output like llama.cpp . Closes #46 
Example output:
```
feed_prompt_duration: 1615ms
prompt_tokens: 10
predict_duration: 6917ms
predict_tokens: 30
per_token_duration: 230.567ms
```

feat: record inference stats

---

llama-cli/src/cli_args.rs
llama-cli/src/main.rs
llama-rs/src/lib.rs

This change adds a `--float-16` flag which allows using a 16 bit float for the model memory key and value tensors. 
The `--float-16` flag enables it for both K and V, however internally it is possible to set it independently (I don't know why you'd want to, but...)
In addition to saving memory, this change only reduces the size of the cached prompt by about 50% when enabled.
Should complete #51.

Add --float16 (was --float-16) to llama-cli and associated support to llama-rs

---

llama-cli/src/cli_args.rs
llama-cli/src/main.rs
llama-rs/src/lib.rs

`--bias-tokens` allows passing a list of token ids and float point biases. This can be used to emulate llama.cpp's `--ignore-eos` feature in a more flexible way. For example using `--bias-tokens 2=-1` will prevent the EOD token from being generated and the model will just ramble on until it hits the context limit.
`--dump-prompt-tokens` will just dump the tokens for the prompt after loading, in two formats: First just as a list of token ids and then as a list with the associated string the token came from. For example, with prompt `What a kerfuffle!`, you'd get the output:
=== Dumping prompt tokens:
5618, 263, 13023, 21154, 600, 280, 29991
"What":5618, " a":263, " ker":13023, "fu":21154, "ff":600, "le":280, "!":29991
***
Some minor backend changes were necessary to make this possible but …

Add --bias-tokens and --dump-prompt-tokens flags and associated backend changes.

---

llama-rs/src/ggml.rs
llama-rs/src/lib.rs

Latest ggml models have:
- Different magic
- A format version
- Scores for tokens (currently parsed but unused)
This PR maintains support for older ('legacy') models
A model downloaded and converted on latest master in `llama.cpp` now works with `llama-rs` but the output seems qualitatively worse. Haven't played around much with `llama-rs` though so it's hard to say whether this is a regression.

Support latest (breaking) changes to GGML file format

---

llama-rs/src/lib.rs

Import fixes for magic (https://github.com/setzer22/llama-rs/issues/59#issuecomment-1479910799). 
Fix 65B model error (https://github.com/setzer22/llama-rs/issues/65).
A better fix for the memory allocation issue is probably possible, but this works without any impact on memory for any model (tested 7B: 4G, 13B: 5G, 30B: 20G, 65B: 39G).

fix 65B model 

---

llama-cli/src/main.rs
llama-rs/src/lib.rs

See https://github.com/ggerganov/llama.cpp/pull/439
Closes #67
I'm not necessarily proposing to merge this, just putting it here in case it's useful.
***
From my very, _very_, **very** unscientific testing, it seems like this does very slightly increase memory usage and also increases token generation time a little bit.
These notes are super unscientific, but included just in case it's useful. Also note these tests on were on a machine running other applications like VS Code, web browsers, etc. The tests with the 30B model are close to my machine's memory limit (32GB) so may have caused some swapping as well.
The differences are definitely in the margin of error just because the tests weren't very controlled. (It also did seem like it made more of a difference with 12 threads vs 6. My CPU …

Copy v_transposed like llama.cpp

---

llama-cli/src/main.rs
llama-rs/src/lib.rs

The default value was being used regardless of the value provided by the user.

Fix for the --batch-size parameter

---

examples/alpaca_prompt.txt
llama-cli/src/cli_args.rs
llama-cli/src/main.rs

Simple fix that enables the use of
`-f examples/alpaca_prompt.txt -p "Why are large language models so impressive?"`
We should split apart the various tools/modes in the CLI sooner rather than later. I'll do that once #83 lands.

feat: replace $PROMPT in prompt files in non-REPL

---

llama-cli/src/cli_args.rs

Some previous changes broke the num_threads flag in `llama_cli`. This PR restores the original behavior of obeying the value for the -t flag, and only using the autodetected value when none is set.

Fix num_threads flag being ignored

---

scripts/convert-pth-to-ggml.py

The version of the `convert-pth-to-ggml` script we had was for GGJT, which we don't support. This fixes it by pulling the script from https://github.com/ggerganov/llama.cpp/blob/a5c42c4b13b3be9e58fe8f9adbb6ee60417674a6/convert-pth-to-ggml.py

scripts: use GGMF version of convert-pth-to-ggml.py

---

ggml-sys/build.rs

Hi, this should solve the apple m1 targeting cross compile problem. We should check if host platform is same as target platform, if same, we enable mcpu=native, otherwise we manually setup the flags

fix: cross compile from non-apple silicon host to apple silicon

---

ggml-sys/ggml/CREDITS.txt
ggml-sys/ggml/ggml.c
ggml-sys/ggml/ggml.h
ggml-sys/src/lib.rs
ggml/src/lib.rs
llama-cli/src/cli_args.rs
llama-rs/src/lib.rs

This would have been a pretty interesting first issue.
This also includes nuking the `increased_determinism` option since it's no longer needed.
I confirmed that it's possible to change the thread/batch sizes with deterministic results. I haven't don't any extensive performance testing but there didn't seem to be an obvious issue.
Other people should probably do some testing before this gets merged as it's a fairly complicated change. I can't say I really understood what I was porting across.
Closes #118
Closes #67

Sync to llama.cpp + GGML version as of 20230407 09:57 AM UTC.

---

ggml-sys/ggml/CREDITS.txt
ggml-sys/ggml/ggml.c
ggml-sys/ggml/ggml.h
ggml-sys/src/lib.rs

A quick sync since I was looking at this code anyway for something else. The changes don't seem very exciting, I think it's just some internal reorganization of quantization functions. I'm not sure it's a user visible change from our side but it could affect the work on the quantization utility.
This only includes the GGML changes. I read through the changes in `llama.cpp` itself and it didn't look like there was anything that we'd care about (they cleaned up the loading process). It didn't seem like it affected inference but I may have missed something.
Link to delta between this and the previous update: https://github.com/ggerganov/llama.cpp/compare/cc9cee8e9e7598bd280295f6264f36d3a9224006..180b693a47b6b825288ef9f2c39d24b6eea4eea6

Sync to GGML version as of 20230410 10:00 AM UTC.

---

Cargo.lock
llama-cli/Cargo.toml
llama-cli/src/main.rs
llama-cli/src/snapshot.rs
llama-rs/Cargo.toml
llama-rs/src/lib.rs

While writing up #122, I realised it doesn't really make sense to be prescriptive about how to read or write a snapshot to disk. This PR moves all read/write logic to the CLI, and leaves the snapshot/ref as Serde-compatible so that users can make their own decisions on how to snapshot.
The main benefit of this is that it removes the `bincode` dependency from the library.

refactor(llama): remove bincode

---

ggml/src/lib.rs
llama-cli/src/cli_args.rs
llama-rs/src/convert.rs
llama-rs/src/lib.rs

As discussed on Discord and in #11.
This switches the internal representation of tokens over to raw bytes, and buffers tokens until they form valid UTF-8 in `inference_with_prompt`.
Open questions:
1) Should we use `smallvec` or similar for tokens? We're going to be making a *lot* of unnecessary tiny allocations as-is.
2) `FnMut` as a bound is OK, right?

fix(llama): buffer tokens until valid UTF-8

---

ggml/src/lib.rs
llama-rs/src/lib.rs

This attempts to fix https://github.com/rustformers/llama-rs/issues/115
Not the brightest of code. Scratch buffer usage is imitated from llama.cpp. `evaluate` context memory reservation is also imitated there (or at least that's the attempt). Note that I didn't actually go through all the things in llama.cpp, only the ones related to context memory size, so I might be missing something.
I'm quite sure this allocates a lot more extra memory for 7B and 13B models as well, even though I never had any issues with them running out of context memory. Scratch buffers take 1GB, and that's for every `InferenceSession`.
Maybe it would make sense to only use scratch buffers for inferring bigger models only? Though I think llama.cpp uses them always. Also, if there are multiple sessions, scratch …

Reserve more eval memory and use ggml scratch buffers

---

ggml-sys/ggml/CREDITS.txt
ggml-sys/ggml/ggml.c
ggml-sys/ggml/ggml.h
ggml-sys/src/lib.rs
ggml/src/lib.rs

This also exposes the unary and binary map operations in the `ggml` crate.
Doesn't appear to be any inference related changes in `llama.cpp` itself so nothing to worry about there.

Sync to GGML version as of 20230414 06:00 AM UTC.

---

ggml-sys/ggml/CREDITS.txt
ggml-sys/ggml/ggml.c
ggml-sys/ggml/ggml.h
ggml-sys/src/lib.rs

Just padding the contributor stats with code I didn't write, no big deal...
On a more serious note, this one actually has some interesting stuff since they added 8 bit quantization and some 4 bit operations now use that for the intermediate results for increased accuracy. This _should_ provide better results when running 4 bit quantized models. See:
1. https://github.com/ggerganov/llama.cpp/issues/909
2. https://github.com/ggerganov/llama.cpp/pull/951
There weren't any non-GGML changes that would affect us.
I can't see how it would be a reason to hold off, but I guess it's worth mentioning this will almost certainly lead to different results relative to the previous version even when using a specific seed. (At least for 4 bit quantized models.)
***
Is submitting this many pulls for …

Sync to GGML version as of 20230416 08:55 AM UTC.

---

llama-cli/Cargo.toml
llama-cli/src/cli_args.rs
llama-cli/src/main.rs

We have nice error messages via `thiserror` - let's use them! 
This PR uses `color_eyre` to get fancier error messages, including tracking context around errors to make debugging easier.
There's probably more error handling we could convert to this approach, but this is decent starting point.

Add color_eyre for cli error handling

---

ggml-loader/Cargo.toml
ggml-loader/src/lib.rs
ggml-loader/src/util.rs
ggml/src/lib.rs
llama-cli/src/cli_args.rs
llama-cli/src/main.rs
llama-rs/src/convert.rs
llama-rs/src/inference_session.rs
llama-rs/src/lib.rs
llama-rs/src/loader.rs
llama-rs/src/loader2.rs
llama-rs/src/loader_common.rs
llama-rs/src/model.rs

As noticed by @KerfuffleV2, both loaders incorrectly handle newer models that mix tensor types indiscriminately due to a confusion between the `ftype/f16_` and element type.
I was planning on bringing #84 up to date first, but realised that I needed to figure out what was going on with `ftype` before baking that in.
I've addressed the issue by decoupling them properly, and then switching over to loading the tensors from file instead of trying to preallocate them with the wrong type. This mirrors the changes made in https://github.com/ggerganov/llama.cpp/pull/801.
I've tested this with Alpaca 7B GGML and `gpt4-x-alpaca-13b-native-4bit-128g`, the latter with and without `mmap`, and all seems to work.
---
I'm not happy at how I broke the isolation between the loader and the `Model` with …

fix #149 - load tensors by type, ignoring filetype

---

llama-rs/src/loader_common.rs

This makes it easier to see why a given model isn't loading, since it'll now print the mismatched magic number in the stack of errors.

Add discovered number to magic mismatch error

---

llama-rs/src/loader2.rs

Present the error from reading the file, rather than an error about multipart support.

fix: Proper error message when the model file doesn't exist

---

llama-rs/src/loader.rs
llama-rs/src/loader2.rs
llama-rs/src/util.rs

Linux man page says about MAP_POPULATE
MAP_POPULATE (since Linux 2.5.46)
Populate (prefault) page tables for a mapping.  For a file
mapping, this causes read-ahead on the  file.   This  will
help  to reduce blocking on page faults later.  The mmap()
call doesn't fail if the mapping cannot be populated  (for
example,  due  to limitations on the number of mapped huge
pages when using MAP_HUGETLB).  Support  for  MAP_POPULATE
in  conjunction  with  private mappings was added in Linux
2.6.23.

mmap with MAP_POPULATE

---

crates/llm-base/src/model.rs

As `KnownModel` implements `Send` and `Sync` and everything that implements `KnownModel` also implements `Model`, `Model` should also implement `Send` and `Sync`.

Added Send + Sync to Model

---

binaries/llm-cli/src/cli_args.rs
crates/llm-base/src/loader.rs

We were previously cloning too much, causing even `mmap` file loads to be fairly slow.  After this patch, load times for alpaca-65b drop from 300ms minimum to ~6ms on my machine.  Similarly, I now get ~16s load times for `--no-mmap`.
I also snuck in a change to render the spinner less frequently, since `spinoff` apparently throws away spinner state on `update_text()` calls. I'm too lazy to make a second PR and that's arguably related to loading perf, so here it is.

Speed up model loading

---

crates/llm-base/src/util.rs

Small QOL fix.
Currently when the model is in the current directory, using the model name directly throws awkward "non-specific I/O error".
Better to simply check if we're in the current directory.

Consider current directory if parent directory is blank

---

flake.lock
flake.nix

This PR adds a [Nix Flake](https://nixos.wiki/wiki/Flakes) for building and distributing the binary.
```console
$ nix run "github:rustformers/llm?submodules=1"
A CLI for running inference on supported Large Language Models. Powered by the `llm` library.
Usage: llm <COMMAND>
Commands:
llama  Use a LLaMA model
bloom  Use a BLOOM model
gpt2   Use a GPT-2 model
gptj   Use a GPT-J model
...
```

nix: add flake

---

crates/llm-base/src/inference_session.rs
crates/llm-base/src/model/mod.rs
crates/models/bloom/src/lib.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/llama/src/lib.rs
crates/models/neox/src/lib.rs

This fixes the issue, but I'm still not sure if it's the *right* fix per se.

fix #187 - skip over the BOS token for BLOOM

---

crates/llm-base/src/model/mod.rs
crates/models/bloom/src/lib.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/llama/src/lib.rs
crates/models/neox/src/lib.rs

Pretty simple refactor - removes the duplicated `load` and moves it to the trait.

refactor: move load to KnownModel trait

---

Cargo.lock
binaries/llm-cli/src/cli_args.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/vocabulary.rs
crates/llm/Cargo.toml
crates/llm/src/lib.rs

- `ModelArchitecture` implements `Serialize`
- `FromStr::Err` for `TokenBias` implements `Error`
Ref: https://github.com/sobelio/llm-chain/pull/116#discussion_r1186730511

Refactors from llm-chain integration

---

.vscode/launch.json
Cargo.lock
Cargo.toml
binaries/llm-cli/Cargo.toml
binaries/llm-cli/src/main.rs
crates/llm-base/src/inference_session.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/util.rs
crates/llm/Cargo.toml
crates/llm/examples/inference.rs
crates/llm/examples/vicuna-chat.rs
crates/llm/src/lib.rs

Fine-grain inference feedback

---

.vscode/launch.json
Cargo.lock
Cargo.toml
README.md
binaries/llm-cli/src/cli_args.rs
binaries/llm-cli/src/main.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/loader.rs
crates/llm-base/src/model/mod.rs
crates/llm/Cargo.toml
crates/llm/examples/inference.rs
crates/llm/examples/vicuna-chat.rs
crates/llm/src/lib.rs
crates/models/bloom/src/lib.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/llama/Cargo.toml
crates/models/llama/src/lib.rs
crates/models/neox/Cargo.toml
crates/models/neox/src/lib.rs
known-good-models.md

Tested with https://huggingface.co/keldenl/RedPajama-INCITE-Chat-7B-v0.1-GGML/tree/main

Implement RedPajama as a NeoX Specialization

---

crates/ggml/src/format/loader.rs
crates/llm-base/src/loader.rs
crates/llm-base/src/lora.rs

The hardcoded context size resulted in errors, while loading adapters with larger tensors. To fix this the context  size is now calculated dynamically via the dimensions of the tensors.
Tested with this adapter: https://huggingface.co/LLukas22/vigogne-instruct-7b-lora-ggml and a 7B  LLaMA model.

Dynamically calculate the LoRA patching context size

---

binaries/llm-cli/src/cli_args.rs

Otherwise we'll print the error trace on the same line as the spinner.

fix: cancel the loading spinner in error cases

---

Cargo.lock
Cargo.toml
binaries/llm-cli/src/cli_args.rs
binaries/llm-cli/src/main.rs
crates/ggml/Cargo.toml
crates/ggml/src/format/saver.rs
crates/ggml/src/lib.rs
crates/ggml/src/tests.rs
crates/llm-base/src/loader.rs
crates/llm-base/src/lora.rs
crates/llm-base/src/model/mod.rs
crates/llm-base/src/quantize.rs
crates/models/bloom/src/lib.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/gptneox/src/lib.rs
crates/models/llama/src/lib.rs
crates/models/mpt/src/lib.rs

As requested by @LLukas22, this adds a `-c` option to `quantize` that lets you output GGML files. This should enable compatibility with the GGML example implementations of GPT-NeoX etc.

feat: support quantizing with a GGML container

---

binaries/llm-cli/src/cli_args.rs
binaries/llm-cli/src/main.rs
crates/llm-base/src/inference_session.rs
crates/llm-base/src/util.rs

Borrowed the implementation from https://huggingface.co/docs/transformers/perplexity
llama.cpp implements it a little differently, and their implementation does not work on prompts of size less than the context window.
For the interface, I added a simple cli-arg to run a perplexity check.
Solves https://github.com/rustformers/llm/issues/90.

Add perplexity calculation and cli-arg

---

binaries/llm-cli/src/cli_args.rs
binaries/llm-cli/src/main.rs
crates/ggml/src/util.rs
crates/llm/src/lib.rs
crates/models/gptneox/src/lib.rs

This adds the new boolean `use_parallel_residual` hyperparameter to the Gpt-Neox implementation.
This also enables us to remove the RedPajama model overwrite.
I will use this branch to convert and quantize the models published by [Together](https://huggingface.co/togethercomputer).

Update Gpt-NeoX implementation

---

binaries/llm-cli/src/cli_args.rs
binaries/llm-cli/src/main.rs
crates/llm-base/src/inference_session.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/vocabulary.rs
crates/llm/examples/inference.rs
crates/llm/examples/vicuna-chat.rs
crates/llm/src/lib.rs

There were some errors (one quite big) with https://github.com/rustformers/llm/pull/248 for larger files which caused it to panic with a large context window.
I believe this fixes most of those cases. I'm limited in my testing abilities, so if someone else could run perplexity checks for a few models, that would be better.

Fix perplexity calculation

---

crates/models/gptneox/src/lib.rs

Fixes #246.
The [tokenization behaviour](https://github.com/rustformers/llm/blob/main/crates/llm-base/src/vocabulary.rs#L123-L126) has to be changed to make this work with every gpt-neox based model.
e.g. Redpajama doesn't like the added padding token at the start of a sequence.

Pull upstream changes into GptNeox 

---

crates/llm-base/src/model/common.rs
crates/llm/examples/embeddings.rs
crates/llm/examples/inference.rs
crates/llm/examples/vicuna-chat.rs
crates/models/llama/src/lib.rs

This is a pull request to fix some errors in the "extract embeddings" section of the original code in the repository. The running results of the code after the corrections were made when obtaining embeddings are shown below.
**The Result of calculating the cosine similarity using the fixed code and llama.cpp:**
**Query Text:** ”My favourite animal is the dog“
| Text | Similarity(LLaMA.cpp) | Similarity(Fixed Code) |
| - | - | - |
| “My favourite animal is the dog” | 1 | 0.99999999 |
| “My favourite animal is the cat” | 0.928901 | 0.92852515 |
| ”I have just adopted a cute dog“ | 0.70601 | 0.596631 |
**The first 10 elements of text embeddings, the length of all embeddings is 4096:**
> 1. Query Text: "My favourite animal is the dog"
**Fixed Code:** 
`[1.6758084, -0.10050424, -0.3598353, …

Fix embeddings extraction

---

crates/ggml/src/tests.rs
crates/models/mpt/src/lib.rs

Add scratchbuffers similar to the upstream ggml examples of GptNeoX/MPT. Should reduce memory consumption.

Add scratchbuffers to MPT

---

crates/llm/examples/embeddings.rs
crates/models/bloom/src/lib.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/gptneox/src/lib.rs
crates/models/mpt/src/lib.rs

Apply the fixed code for embeddings extraction to all models to avoid assertion errors. #288

Fix embeddings extraction for all models

---

binaries/llm-cli/src/cli_args.rs

Fixes #297.  Seems like the fields here were accidentally copy-pasted into two different structs.

Fix `--help` panicing in debug mode

---

binaries/llm-cli/src/cli_args.rs
crates/llm-base/src/inference_session.rs

Using 32bit values doesn't increase quality in a measurable way, see discussion here: https://github.com/ggerganov/llama.cpp/discussions/1593
The current default doubles memory consumption/size of prompt caches without a measurable upside. This pull changes the default to 16bit.
Allows `--float16` for backward compatibility.
Adds `--no-float16` flag to allow using 32bit memory.
***
Don't know if it's just me but I can't even run `llm llama infer --help` from the main branch:
```
The application panicked (crashed).
Message:  Command infer: Argument names must be unique, but 'vocabulary_path' is in use by more than one argument or group
```

Default to f16 model memory k/v in llm CLI and InferenceSessionConfig

---

crates/ggml/sys/build.rs

Alternate fix to #324 (thanks for the inspiration!)
The Rust build script has the ability to create new files, and use them as fodder for the build process. We can use this to create an alternate `ggml-metal.m` that embeds the Metal shader source code and sidestep the issue of runtime loading entirely.
Let me know if you're OK with this @pixelspark @nightscape !

fix(metal): patch ggml-metal.m with shader code

---

.github/workflows/rust.yml
.rusty-hook.toml
Cargo.lock
binaries/llm-cli/Cargo.toml
binaries/precommit-check/Cargo.toml
binaries/precommit-check/README.md
binaries/precommit-check/src/main.rs
doc/CONTRIBUTING.md

I'm very bad at running checks locally before making commits, so I figured I'd make it everyone else's problem.
This uses `rusty-hook` to set up a Git pre-commit hook that ensures that your commit will not fail CI.
I could be convinced to make it a pre-push hook, but I think this is the right call.

feat: automatically run checks before commit

---

crates/llm-base/src/lib.rs
crates/llm/src/lib.rs

Does what it says on the tin. `InferenceSnapshotRef` should be used to Serialize, `InferenceSnapshot` should be used to Deserialize, so we want to stick them together.

Added InferenceSessionRef to exports, for easier serializing and deserializing.

---

Cargo.lock
README.md
binaries/llm-cli/Cargo.toml
binaries/llm-cli/src/cli_args.rs
crates/llm-base/Cargo.toml
crates/llm-base/src/tokenizer/mod.rs
crates/llm/Cargo.toml

Using a remote tokenizer from huggingface isn't advisable in prod, and so the features to enable that aren't necessarily needed all the time. This PR introduces a feature flag `tokenizers-remote` which is on by default. When turned off, the Remote option for tokenizers is disabled.
The main win here for me at least is the removal of OpenSSL in a production environment. I deploy to various environments, many of which have no OpenSSL installation, and since I don't use a remote tokenizer, it's unnecessary.

Added tokenizers-remote

---

crates/llm-base/src/loader.rs
crates/llm/src/lib.rs

When providing an incorrect model architecture:
```
error: invalid value 'llama1' for '--model-architecture <MODEL_ARCHITECTURE>': llama1 is not one of supported model architectures: [Bloom, Gpt2, GptJ, GptNeoX, Llama, Mpt]
```
It is much easier for users to know what available model architectures are.

Improve model architecture error message

---

binaries/llm-cli/src/cli_args.rs

When playing with chat command and just found that it doesn't check if provided message prompt and message prompt contain correct placeholder. If it is not, no proper feedback to users and users won't know the prompt isn't actually generated to the model.

Add placeholder check for message prompt

---

.github/workflows/rust.yml
crates/ggml/sys/build.rs

Closes https://github.com/rustformers/llm/issues/342.
Adds CI for metal/cuda and clblast builds to ensure they can be built.

Fix linux CLBlast build and add CI for accelerated builds  

---

.github/workflows/rust.yml

Adds cublas builds to CI. 
Currently the cuda-toolkit setup on a windows runner takes ~15 min (see https://github.com/Jimver/cuda-toolkit/issues/253), maybe we should disable the the windows cuda ci for the time being?

Add CI for cuda builds

---

binaries/llm-test/configs/bloom.json
binaries/llm-test/configs/gptj.json
binaries/llm-test/configs/gptneox.json
binaries/llm-test/configs/llama.json
binaries/llm-test/configs/mpt.json
binaries/llm-test/src/common.rs
binaries/llm-test/src/delete.rs
binaries/llm-test/src/inference.rs
binaries/llm-test/src/main.rs
binaries/llm-test/src/tokens.rs
crates/ggml/sys/build.rs
crates/llm-base/src/inference_session.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/model/mod.rs
crates/llm/src/lib.rs
crates/models/bloom/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/gptneox/src/lib.rs
crates/models/llama/src/lib.rs
crates/models/mpt/src/lib.rs

The **goal** of this PR is to enable token feed undo. This is mostly useful for autocomplete functionality (e.g. keyboards or coding assistants), where the text changes often around the cursor's position.
Closes https://github.com/rustformers/llm/issues/332
**Tested** on `GptNeoX` by writing a demo program that uses the `delete_token` method to minimize model refreshes. I tested these use cases:
* Add 200 tokens, then delete one of them. Ensure topk predictions look the same as before the latest token.
* Add 200 tokens, then delete all of them. Ensure topk predictions return to start of sentence.
* Delete then add, add then delete, etc.
* Used println!() extensively to verify it was deleting the expected tokens.
The **performance** is pretty solid. Deleting 10 tokens takes less than a …

Add ability to delete tokens (undo feed)

---

crates/ggml/src/context.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/gptneox/src/lib.rs

Closes #338 
Based off of https://github.com/rustformers/llm/pull/343
Fixes the segfault issue mentioned in that bug, and adds a check that could help catch those errors faster.

Update gpt2 to use wte if no lm_head

---

Cargo.lock
Cargo.toml
binaries/llm-cli/Cargo.toml
binaries/llm-cli/src/main.rs
crates/llm-base/Cargo.toml
crates/llm-base/src/inference_session.rs
crates/llm-base/src/loader.rs
crates/llm/Cargo.toml
crates/models/llama/Cargo.toml
crates/models/llama/src/lib.rs

Hi, everyone!
First, thanks for the project!
This commit begins adding tracing and some instrumentation to this project.
As folks are beginning to look at using and optimising this project, I suspect this will be very useful.
Below is an example of sending the data to an open telemetry collector and visualising it:
This is a draft PR for now, as we understand whether this is something we would like to add to the project.
If it is, this can be expanded to include more robust logging and instrumentation.

feat(tracing): add tracing to `llm` and `llm-base` crates

---

Cargo.lock
Cargo.toml
binaries/llm-cli/Cargo.toml
binaries/llm-cli/src/cli_args.rs
binaries/llm-cli/src/interactive.rs
binaries/llm-cli/src/main.rs
binaries/llm-test/Cargo.toml
binaries/llm-test/src/inference.rs
crates/llm-base/Cargo.toml
crates/llm-base/src/inference_session.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/samplers.rs
crates/llm-base/src/tokenizer/mod.rs
crates/llm/src/lib.rs

**Warning**: This is very lightly tested (but appears to work).
This pull adds optional (and off by default) integration with my `llm-samplers` crate ( https://crates.io/crates/llm-samplers ) which supports building modular sampler chains and includes all the samplers that `llama.cpp` currently supports.
I tried to implement this in a non-invasive way.
The pull adds support for:
* Mirostat v1 and v2 samplers
* Locally typical sampling
* Tail free sampling
* Frequency and presence penalties
Of course it supports all the existing sampler types as well.
*Caveats*: Right now using Mirostat v1 is really awkward because it needs to know the model vocabulary size but it doesn't seem like that information is available at the time the samplers are constructed. I made it a commandline option, but …

Use llm_samplers crate for sampler backend

---

crates/llm-base/Cargo.toml

This commit removes the pinned version of the `half` crate, allowing consumers to resolve to a version of `half` that is compatible with other dependencies in the project.
I'm not sure if pinning to this exact version was intended — happy to close if this causes unintended behavior.
Thanks!

fix(deps): remove pinned `half` dependency

---

crates/ggml/src/accelerator/metal.rs
crates/ggml/src/context.rs
crates/ggml/src/lib.rs
crates/ggml/sys/src/cuda.rs
crates/ggml/sys/src/lib.rs
crates/llm-base/src/inference_session.rs
crates/llm-base/src/lora.rs
crates/models/bloom/src/lib.rs
crates/models/falcon/src/lib.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/gptneox/src/lib.rs
crates/models/llama/src/lib.rs
crates/models/mpt/src/lib.rs
doc/acceleration-support.md

Removes the `op_repeat` ggml operation and replaces it with broadcasting. 
This should enable the gpu acceleration of: `gpt2`, `gptj`, `gptneox` and `falcon`
Also fixes: https://github.com/rustformers/llm/issues/391

Remove `repeat` operation and add acceleration support for other architectures

---

crates/ggml/Cargo.toml
crates/ggml/src/context.rs
crates/ggml/src/format/loader.rs
crates/llm-base/src/inference_session.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/loader.rs
crates/llm-base/src/lora.rs
crates/llm-base/src/model/mod.rs
crates/models/bloom/src/lib.rs
crates/models/falcon/src/lib.rs
crates/models/gpt2/src/lib.rs
crates/models/gptj/src/lib.rs
crates/models/gptneox/src/lib.rs
crates/models/llama/src/lib.rs
crates/models/mpt/src/lib.rs

Was trying to work on #412, but ended up side-tracked by this. The most problematic thing is the `Arc` non-`Send`/`Sync` lint; I went back and forth on this, but I was able to mostly convince myself that our current use is OK because we offer abstractions with different sync guarantees.
Still not 100% convinced though, I feel like our GGML bindings need a rethink to better fit Rust safety guarantees 😅

Rust 1.72 fixes

---

crates/ggml/README.md

Minor typo  found in ggml readme:
`1.0` instead of `1.1` in tensor explanation

Fix typo in README.md

---

crates/ggml/sys/build.rs

During a build using Jenkins agent I got an error `-mcpu=native` is not available for clang

Fix build on macos m1

---

crates/llm-base/src/inference_session.rs

`n_past` can be bigger then `tokens.len()` it should not be used to drain `tokens` array

Fix rewind crash

---

Cargo.lock
Cargo.toml
binaries/llm-cli/src/cli_args.rs
binaries/llm-test/src/inference.rs
crates/llm-base/src/lib.rs
crates/llm-base/src/samplers.rs

See https://github.com/KerfuffleV2/llm-samplers/pull/9 for more information about the changes.
Notable features are adding Top-A and Min-P samplers.

Update to llm-samplers v0.0.7

---

Cargo.lock
Cargo.toml
binaries/llm-cli/src/cli_args.rs
binaries/llm-cli/src/interactive.rs

This required bumping other dependencies and hacking up the Cargo.lock.

chore: update rustix 0.38

---

crates/llm/src/lib.rs

When building a project with 1.74.0-nightly `rustc` compiler, I receive a warning further described by this thread.
https://github.com/rust-lang/rust/issues/115010

fix &'static lifetime warning
